name: 🌙 Nightly E2E Tests

on:
  schedule:
    # Run every day at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    name: Run E2E Tests (Production)
    timeout-minutes: 30

    strategy:
      matrix:
        # Run on all browsers for comprehensive testing
        browser: [chromium, firefox, webkit, 'Mobile Chrome', 'Mobile Safari']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'playwright/package-lock.json'

      - name: Install Playwright dependencies
        working-directory: ./playwright
        run: npm ci

      - name: Install Playwright browsers
        working-directory: ./playwright
        run: npx playwright install --with-deps

      - name: Run E2E tests against production
        working-directory: ./playwright
        run: npx playwright test --project=${{ matrix.browser }}
        env:
          CI: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-test-results-${{ matrix.browser }}
          path: |
            playwright/test-results/
            playwright/test-results.xml
            playwright/test-results.json
          retention-days: 30

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright/playwright-report/
          retention-days: 30

      - name: Comment on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('🌙 Nightly E2E Tests failed')
            );

            const commentBody = `🌙 **Nightly E2E Tests failed**

            The nightly E2E tests have failed against production (portfolio.nergy.space). Please check the test results and fix any issues.

            - [View Test Results](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})
            - [Download Test Artifacts](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}/artifacts)

            This is an automated message from the nightly E2E test workflow.`;

            if (botComment) {
              await github.rest.issues.updateComment({
                comment_id: botComment.id,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentBody,
              });
            } else {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentBody,
              });
            }
