name: 🧪 E2E Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    name: Run E2E Tests
    timeout-minutes: 20

    strategy:
      matrix:
        # Run on multiple browsers for comprehensive testing
        browser: [chromium, 'Mobile Chrome']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'playwright/package-lock.json'

      - name: Cache Playwright browsers
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
            ~/.cache/ms-playwright-github
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('playwright/package-lock.json') }}
          restore-keys: |
            playwright-browsers-${{ runner.os }}-

      - name: Install Playwright dependencies
        working-directory: ./playwright
        run: npm ci

      - name: Install Playwright browsers
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        working-directory: ./playwright
        run: npx playwright install --with-deps

      - name: Run E2E tests
        working-directory: ./playwright
        run: npx playwright test --project="${{ matrix.browser }}"
        env:
          CI: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-test-results-${{ matrix.browser }}
          path: |
            playwright/test-results/
            playwright/test-results.xml
            playwright/test-results.json
          retention-days: 7

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright/playwright-report/
          retention-days: 7
