name: 🌙 Nightly E2E Tests

on:
  schedule:
    # Run every day at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  e2e-chrome-and-firefox-and-chrome-mobile:
    runs-on: ubuntu-latest
    name: Run E2E Tests (Production)
    timeout-minutes: 30

    strategy:
      matrix:
        # Run on all browsers for comprehensive testing
        browser: [chromium, firefox, 'Mobile Chrome']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'playwright/package-lock.json'

      - name: Cache Playwright browsers
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
            ~/.cache/ms-playwright-github
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('playwright/package-lock.json') }}
          restore-keys: |
            playwright-browsers-${{ runner.os }}-

      - name: Install Playwright dependencies
        working-directory: ./playwright
        run: npm ci

      - name: Install Playwright browsers
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        working-directory: ./playwright
        run: npx playwright install --with-deps

      - name: Run E2E tests against production
        working-directory: ./playwright
        run: npx playwright test --project="${{ matrix.browser }}"
        env:
          CI: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-test-results-${{ matrix.browser }}
          path: |
            playwright/test-results/
            playwright/test-results.xml
            playwright/test-results.json
          retention-days: 30

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright/playwright-report/
          retention-days: 30

  e2e-safari-and-mobile-safari:
    runs-on: macos-latest
    name: Run E2E Tests (Safari)
    timeout-minutes: 30

    strategy:
      matrix:
        browser: [Safari, 'Mobile Safari']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: playwright/package-lock.json

      - name: Cache Playwright browsers
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
            ~/.cache/ms-playwright-github
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('playwright/package-lock.json') }}
          restore-keys: |
            playwright-browsers-${{ runner.os }}-

      - name: Install dependencies
        working-directory: ./playwright
        run: npm ci

      - name: Install Playwright browsers
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        working-directory: ./playwright
        run: npx playwright install webkit

      - name: Run E2E tests on Safari
        working-directory: ./playwright
        run: npx playwright test --project="${{ matrix.browser }}"
        env:
          CI: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-test-results-${{ matrix.browser }}
          path: |
            playwright/test-results/
            playwright/test-results.xml
            playwright/test-results.json
          retention-days: 30

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright/playwright-report/
          retention-days: 30
