name: Docker Image Push

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  buildDockerImage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t nergy101/portfolio:v1 .

  pullAndRunDockerImageOnVM:
    runs-on: ubuntu-latest

    steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Connect to Droplet
      run:  |
            doctl compute ssh nergy --ssh-command docker pull nergy101/portfolio:v1 \
            docker stop portfolio \
            docker rm portfolio \
            docker run --restart unless-stopped -p 8080:80 -d --name portfolio nergy101/portfolio:v1

